server:
  port: 8762

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:./config
  profiles:
    active:
    - native
    - @activeProfile@
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
  instance:
    prefer-ip-address: true
